# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/deng/GameFcgi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/deng/GameFcgi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/deng/GameFcgi/CMakeFiles /home/deng/GameFcgi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/deng/GameFcgi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named reg

# Build rule for target.
reg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reg
.PHONY : reg

# fast build rule for target.
reg/fast:
	$(MAKE) -f CMakeFiles/reg.dir/build.make CMakeFiles/reg.dir/build
.PHONY : reg/fast

#=============================================================================
# Target rules for targets named login

# Build rule for target.
login: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 login
.PHONY : login

# fast build rule for target.
login/fast:
	$(MAKE) -f CMakeFiles/login.dir/build.make CMakeFiles/login.dir/build
.PHONY : login/fast

CJsonObject-1.0/CJsonObject.o: CJsonObject-1.0/CJsonObject.cpp.o

.PHONY : CJsonObject-1.0/CJsonObject.o

# target to build an object file
CJsonObject-1.0/CJsonObject.cpp.o:
	$(MAKE) -f CMakeFiles/reg.dir/build.make CMakeFiles/reg.dir/CJsonObject-1.0/CJsonObject.cpp.o
	$(MAKE) -f CMakeFiles/login.dir/build.make CMakeFiles/login.dir/CJsonObject-1.0/CJsonObject.cpp.o
.PHONY : CJsonObject-1.0/CJsonObject.cpp.o

CJsonObject-1.0/CJsonObject.i: CJsonObject-1.0/CJsonObject.cpp.i

.PHONY : CJsonObject-1.0/CJsonObject.i

# target to preprocess a source file
CJsonObject-1.0/CJsonObject.cpp.i:
	$(MAKE) -f CMakeFiles/reg.dir/build.make CMakeFiles/reg.dir/CJsonObject-1.0/CJsonObject.cpp.i
	$(MAKE) -f CMakeFiles/login.dir/build.make CMakeFiles/login.dir/CJsonObject-1.0/CJsonObject.cpp.i
.PHONY : CJsonObject-1.0/CJsonObject.cpp.i

CJsonObject-1.0/CJsonObject.s: CJsonObject-1.0/CJsonObject.cpp.s

.PHONY : CJsonObject-1.0/CJsonObject.s

# target to generate assembly for a file
CJsonObject-1.0/CJsonObject.cpp.s:
	$(MAKE) -f CMakeFiles/reg.dir/build.make CMakeFiles/reg.dir/CJsonObject-1.0/CJsonObject.cpp.s
	$(MAKE) -f CMakeFiles/login.dir/build.make CMakeFiles/login.dir/CJsonObject-1.0/CJsonObject.cpp.s
.PHONY : CJsonObject-1.0/CJsonObject.cpp.s

CJsonObject-1.0/cJSON.o: CJsonObject-1.0/cJSON.c.o

.PHONY : CJsonObject-1.0/cJSON.o

# target to build an object file
CJsonObject-1.0/cJSON.c.o:
	$(MAKE) -f CMakeFiles/reg.dir/build.make CMakeFiles/reg.dir/CJsonObject-1.0/cJSON.c.o
	$(MAKE) -f CMakeFiles/login.dir/build.make CMakeFiles/login.dir/CJsonObject-1.0/cJSON.c.o
.PHONY : CJsonObject-1.0/cJSON.c.o

CJsonObject-1.0/cJSON.i: CJsonObject-1.0/cJSON.c.i

.PHONY : CJsonObject-1.0/cJSON.i

# target to preprocess a source file
CJsonObject-1.0/cJSON.c.i:
	$(MAKE) -f CMakeFiles/reg.dir/build.make CMakeFiles/reg.dir/CJsonObject-1.0/cJSON.c.i
	$(MAKE) -f CMakeFiles/login.dir/build.make CMakeFiles/login.dir/CJsonObject-1.0/cJSON.c.i
.PHONY : CJsonObject-1.0/cJSON.c.i

CJsonObject-1.0/cJSON.s: CJsonObject-1.0/cJSON.c.s

.PHONY : CJsonObject-1.0/cJSON.s

# target to generate assembly for a file
CJsonObject-1.0/cJSON.c.s:
	$(MAKE) -f CMakeFiles/reg.dir/build.make CMakeFiles/reg.dir/CJsonObject-1.0/cJSON.c.s
	$(MAKE) -f CMakeFiles/login.dir/build.make CMakeFiles/login.dir/CJsonObject-1.0/cJSON.c.s
.PHONY : CJsonObject-1.0/cJSON.c.s

login.o: login.cpp.o

.PHONY : login.o

# target to build an object file
login.cpp.o:
	$(MAKE) -f CMakeFiles/login.dir/build.make CMakeFiles/login.dir/login.cpp.o
.PHONY : login.cpp.o

login.i: login.cpp.i

.PHONY : login.i

# target to preprocess a source file
login.cpp.i:
	$(MAKE) -f CMakeFiles/login.dir/build.make CMakeFiles/login.dir/login.cpp.i
.PHONY : login.cpp.i

login.s: login.cpp.s

.PHONY : login.s

# target to generate assembly for a file
login.cpp.s:
	$(MAKE) -f CMakeFiles/login.dir/build.make CMakeFiles/login.dir/login.cpp.s
.PHONY : login.cpp.s

reg.o: reg.cpp.o

.PHONY : reg.o

# target to build an object file
reg.cpp.o:
	$(MAKE) -f CMakeFiles/reg.dir/build.make CMakeFiles/reg.dir/reg.cpp.o
.PHONY : reg.cpp.o

reg.i: reg.cpp.i

.PHONY : reg.i

# target to preprocess a source file
reg.cpp.i:
	$(MAKE) -f CMakeFiles/reg.dir/build.make CMakeFiles/reg.dir/reg.cpp.i
.PHONY : reg.cpp.i

reg.s: reg.cpp.s

.PHONY : reg.s

# target to generate assembly for a file
reg.cpp.s:
	$(MAKE) -f CMakeFiles/reg.dir/build.make CMakeFiles/reg.dir/reg.cpp.s
.PHONY : reg.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... reg"
	@echo "... edit_cache"
	@echo "... login"
	@echo "... CJsonObject-1.0/CJsonObject.o"
	@echo "... CJsonObject-1.0/CJsonObject.i"
	@echo "... CJsonObject-1.0/CJsonObject.s"
	@echo "... CJsonObject-1.0/cJSON.o"
	@echo "... CJsonObject-1.0/cJSON.i"
	@echo "... CJsonObject-1.0/cJSON.s"
	@echo "... login.o"
	@echo "... login.i"
	@echo "... login.s"
	@echo "... reg.o"
	@echo "... reg.i"
	@echo "... reg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

